// <auto-generated />
using System;
using LaPlateformeDeLemploiAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaPlateformeDeLemploiAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404174324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaPlateformeDeLemploiAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "bi-code-slash",
                            Name = "Développement Web"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "bi-palette",
                            Name = "Design & UX"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "bi-graph-up",
                            Name = "Data & IA"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "bi-cloud",
                            Name = "DevOps & Cloud"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "bi-shield-lock",
                            Name = "Cybersécurité"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "bi-megaphone",
                            Name = "Marketing Digital"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "bi-kanban",
                            Name = "Gestion de Projet"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "bi-headset",
                            Name = "Support & IT"
                        });
                });

            modelBuilder.Entity("LaPlateformeDeLemploiAPI.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Leader français du développement logiciel, spécialisé dans les solutions cloud innovantes.",
                            Location = "Paris",
                            LogoUrl = "https://ui-avatars.com/api/?name=TC&background=4f46e5&color=fff&size=128",
                            Name = "TechCorp France",
                            Website = "https://techcorp.fr"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Startup spécialisée en intelligence artificielle et analyse de données massives.",
                            Location = "Lyon",
                            LogoUrl = "https://ui-avatars.com/api/?name=DV&background=059669&color=fff&size=128",
                            Name = "DataVision",
                            Website = "https://datavision.io"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Expert en solutions d'infrastructure cloud et DevOps pour entreprises.",
                            Location = "Bordeaux",
                            LogoUrl = "https://ui-avatars.com/api/?name=C9&background=0891b2&color=fff&size=128",
                            Name = "CloudNine",
                            Website = "https://cloudnine.eu"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Agence de design UX/UI primée, créant des expériences numériques mémorables.",
                            Location = "Nantes",
                            LogoUrl = "https://ui-avatars.com/api/?name=DH&background=e11d48&color=fff&size=128",
                            Name = "DesignHub",
                            Website = "https://designhub.fr"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabinet de conseil en cybersécurité protégeant les entreprises du CAC 40.",
                            Location = "Toulouse",
                            LogoUrl = "https://ui-avatars.com/api/?name=CS&background=7c3aed&color=fff&size=128",
                            Name = "CyberShield",
                            Website = "https://cybershield.fr"
                        });
                });

            modelBuilder.Entity("LaPlateformeDeLemploiAPI.Models.JobOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobOffers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CompanyId = 1,
                            ContractType = "CDI",
                            Description = "Nous recherchons un développeur Full Stack passionné pour rejoindre notre équipe produit. Vous travaillerez sur notre plateforme SaaS utilisée par plus de 10 000 entreprises. Stack technique : Angular 19, .NET 8, SQL Server, Azure.",
                            IsActive = true,
                            IsRemote = true,
                            Location = "Paris",
                            PublishedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 60000m,
                            SalaryMin = 45000m,
                            Title = "Développeur Full Stack Angular / .NET"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CompanyId = 2,
                            ContractType = "CDI",
                            Description = "Rejoignez notre équipe Data pour concevoir et déployer des modèles de machine learning en production. Vous travaillerez sur des problématiques de NLP et de computer vision avec des datasets à grande échelle.",
                            IsActive = true,
                            IsRemote = true,
                            Location = "Lyon",
                            PublishedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 75000m,
                            SalaryMin = 55000m,
                            Title = "Data Scientist Senior"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CompanyId = 3,
                            ContractType = "CDI",
                            Description = "Vous serez responsable de la fiabilité et de la scalabilité de notre infrastructure cloud. Kubernetes, Terraform, CI/CD, monitoring et automatisation seront votre quotidien.",
                            IsActive = true,
                            IsRemote = false,
                            Location = "Bordeaux",
                            PublishedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 65000m,
                            SalaryMin = 50000m,
                            Title = "Ingénieur DevOps / SRE"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CompanyId = 4,
                            ContractType = "CDD",
                            Description = "Nous cherchons un designer créatif pour concevoir des interfaces utilisateur exceptionnelles. Vous mènerez des recherches utilisateurs, créerez des wireframes et prototypes, et collaborerez étroitement avec les développeurs.",
                            IsActive = true,
                            IsRemote = true,
                            Location = "Nantes",
                            PublishedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 48000m,
                            SalaryMin = 38000m,
                            Title = "UX/UI Designer"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CompanyId = 5,
                            ContractType = "CDI",
                            Description = "Intégrez notre équipe de pentesters et auditeurs sécurité. Vous réaliserez des tests d'intrusion, des audits de code et accompagnerez nos clients dans leur stratégie de sécurité.",
                            IsActive = true,
                            IsRemote = false,
                            Location = "Toulouse",
                            PublishedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 68000m,
                            SalaryMin = 48000m,
                            Title = "Consultant Cybersécurité"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CompanyId = 1,
                            ContractType = "CDI",
                            Description = "Participez au développement de nos applications web modernes. Vous serez en charge de créer des composants réutilisables, d'optimiser les performances et d'assurer l'accessibilité.",
                            IsActive = true,
                            IsRemote = true,
                            Location = "Paris",
                            PublishedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 55000m,
                            SalaryMin = 42000m,
                            Title = "Développeur Frontend React / Vue.js"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CompanyId = 2,
                            ContractType = "Stage",
                            Description = "Stage de 6 mois au sein de l'équipe Data. Vous participerez à l'analyse de données, la création de dashboards et l'automatisation de rapports avec Python et Power BI.",
                            IsActive = true,
                            IsRemote = false,
                            Location = "Lyon",
                            PublishedAt = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 1200m,
                            SalaryMin = 800m,
                            Title = "Stage Data Analyst"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            CompanyId = 1,
                            ContractType = "CDI",
                            Description = "Pilotez des projets de transformation digitale pour nos clients grands comptes. Méthodologie Agile, gestion budgétaire et coordination d'équipes pluridisciplinaires.",
                            IsActive = true,
                            IsRemote = true,
                            Location = "Paris",
                            PublishedAt = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 65000m,
                            SalaryMin = 50000m,
                            Title = "Chef de Projet Digital"
                        });
                });

            modelBuilder.Entity("LaPlateformeDeLemploiAPI.Models.JobOffer", b =>
                {
                    b.HasOne("LaPlateformeDeLemploiAPI.Models.Category", "Category")
                        .WithMany("JobOffers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaPlateformeDeLemploiAPI.Models.Company", "Company")
                        .WithMany("JobOffers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LaPlateformeDeLemploiAPI.Models.Category", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("LaPlateformeDeLemploiAPI.Models.Company", b =>
                {
                    b.Navigation("JobOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
